// Generated by scripts/generate-wire-types.py — DO NOT EDIT.
// Source: `herdr api schema --json` (protocol 19, schema_version 1).
//
// Stable data types only: the request/response/event envelopes, the
// method/event enums, and the events.subscribe params stay hand-written
// (HerdrWire.kt, HerdrEvents.kt). `<Tag>Response` classes are the
// tagged `result` variants of the success_response schema with the
// redundant `type` tag dropped. Decoding is lenient by construction:
// unknown fields are ignored and closed string sets are raw-string
// value classes, because herdr's API has no stability guarantee.

package dev.bybee.heeler.core.wire

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

@Serializable
data class AgentExplainResponse(
    val explain: JsonElement
)

@Serializable
data class AgentInfo(
    val agent: String? = null,
    @SerialName("agent_session")
    val agentSession: AgentSessionInfo? = null,
    @SerialName("agent_status")
    val agentStatus: AgentStatus,
    val cwd: String? = null,
    @SerialName("display_agent")
    val displayAgent: String? = null,
    val focused: Boolean,
    @SerialName("foreground_cwd")
    val foregroundCwd: String? = null,
    @SerialName("interactive_ready")
    val interactiveReady: Boolean? = null,
    @SerialName("launch_pending")
    val launchPending: Boolean? = null,
    val name: String? = null,
    @SerialName("pane_id")
    val paneID: String,
    val revision: Int,
    @SerialName("screen_detection_skipped")
    val screenDetectionSkipped: Boolean? = null,
    @SerialName("state_change_seq")
    val stateChangeSeq: Int? = null,
    @SerialName("state_labels")
    val stateLabels: Map<String, String>? = null,
    @SerialName("tab_id")
    val tabID: String,
    @SerialName("terminal_id")
    val terminalID: String,
    @SerialName("terminal_title")
    val terminalTitle: String? = null,
    @SerialName("terminal_title_stripped")
    val terminalTitleStripped: String? = null,
    val title: String? = null,
    val tokens: Map<String, String>? = null,
    @SerialName("workspace_id")
    val workspaceID: String
)

@Serializable
data class AgentInfoResponse(
    val agent: AgentInfo
)

@Serializable
data class AgentListResponse(
    val agents: List<AgentInfo>
)

@Serializable
data class AgentPromptParams(
    val target: String,
    val text: String,
    val wait: AgentPromptWaitOptions? = null
)

@Serializable
data class AgentPromptWaitOptions(
    @SerialName("timeout_ms")
    val timeoutMs: Int? = null,
    val until: List<AgentStatus>? = null
)

@Serializable
data class AgentPromptedResponse(
    val agent: AgentInfo
)

@Serializable
data class AgentReadParams(
    val format: ReadFormat? = null,
    val lines: Int? = null,
    val source: ReadSource,
    @SerialName("strip_ansi")
    val stripANSI: Boolean? = null,
    val target: String
)

@Serializable
data class AgentRenameParams(
    val name: String? = null,
    val target: String
)

@Serializable
data class AgentSendKeysParams(
    val keys: List<String>,
    val target: String
)

@Serializable
data class AgentSessionInfo(
    val agent: String,
    val kind: AgentSessionRefKind,
    val source: String,
    val value: String
)

@Serializable
@JvmInline
value class AgentSessionRefKind(val rawValue: String) {
    companion object {
        val id = AgentSessionRefKind("id")
        val path = AgentSessionRefKind("path")
    }
}

@Serializable
data class AgentStartParams(
    val args: List<String>? = null,
    val kind: String,
    val name: String,
    @SerialName("pane_id")
    val paneID: String,
    @SerialName("timeout_ms")
    val timeoutMs: Int? = null
)

@Serializable
data class AgentStartedResponse(
    val agent: AgentInfo,
    val argv: List<String>
)

@Serializable
@JvmInline
value class AgentStatus(val rawValue: String) {
    companion object {
        val idle = AgentStatus("idle")
        val working = AgentStatus("working")
        val blocked = AgentStatus("blocked")
        val done = AgentStatus("done")
        val unknown = AgentStatus("unknown")
    }
}

@Serializable
data class AgentTarget(
    val target: String
)

@Serializable
class OkResponse

@Serializable
data class PaneInfo(
    val agent: String? = null,
    @SerialName("agent_session")
    val agentSession: AgentSessionInfo? = null,
    @SerialName("agent_status")
    val agentStatus: AgentStatus,
    val cwd: String? = null,
    @SerialName("display_agent")
    val displayAgent: String? = null,
    val focused: Boolean,
    @SerialName("foreground_cwd")
    val foregroundCwd: String? = null,
    val label: String? = null,
    @SerialName("pane_id")
    val paneID: String,
    val revision: Int,
    val scroll: PaneScrollInfo? = null,
    @SerialName("state_labels")
    val stateLabels: Map<String, String>? = null,
    @SerialName("tab_id")
    val tabID: String,
    @SerialName("terminal_id")
    val terminalID: String,
    @SerialName("terminal_title")
    val terminalTitle: String? = null,
    @SerialName("terminal_title_stripped")
    val terminalTitleStripped: String? = null,
    val title: String? = null,
    val tokens: Map<String, String>? = null,
    @SerialName("workspace_id")
    val workspaceID: String
)

@Serializable
data class PaneLayoutPane(
    val focused: Boolean,
    @SerialName("pane_id")
    val paneID: String,
    val rect: PaneLayoutRect
)

@Serializable
data class PaneLayoutRect(
    val height: Int,
    val width: Int,
    val x: Int,
    val y: Int
)

@Serializable
data class PaneLayoutSnapshot(
    val area: PaneLayoutRect,
    @SerialName("focused_pane_id")
    val focusedPaneID: String,
    val panes: List<PaneLayoutPane>,
    val splits: List<PaneLayoutSplit>,
    @SerialName("tab_id")
    val tabID: String,
    @SerialName("workspace_id")
    val workspaceID: String,
    val zoomed: Boolean
)

@Serializable
data class PaneLayoutSplit(
    val direction: SplitDirection,
    val id: String,
    val ratio: Double,
    val rect: PaneLayoutRect
)

@Serializable
data class PaneReadParams(
    val format: ReadFormat? = null,
    val lines: Int? = null,
    @SerialName("pane_id")
    val paneID: String,
    val source: ReadSource,
    @SerialName("strip_ansi")
    val stripANSI: Boolean? = null
)

@Serializable
data class PaneReadResponse(
    val read: PaneReadResult
)

@Serializable
data class PaneReadResult(
    val format: ReadFormat,
    @SerialName("pane_id")
    val paneID: String,
    val revision: Int,
    val source: ReadSource,
    @SerialName("tab_id")
    val tabID: String,
    val text: String,
    val truncated: Boolean,
    @SerialName("workspace_id")
    val workspaceID: String
)

@Serializable
data class PaneScrollInfo(
    @SerialName("max_offset_from_bottom")
    val maxOffsetFromBottom: Int,
    @SerialName("offset_from_bottom")
    val offsetFromBottom: Int,
    @SerialName("viewport_rows")
    val viewportRows: Int
)

@Serializable
data class PaneTarget(
    @SerialName("pane_id")
    val paneID: String
)

@Serializable
data class PongResponse(
    val capabilities: ServerCapabilities? = null,
    @SerialName("protocol")
    val protocolVersion: Int,
    val version: String
)

@Serializable
@JvmInline
value class ReadFormat(val rawValue: String) {
    companion object {
        val text = ReadFormat("text")
        val ansi = ReadFormat("ansi")
    }
}

@Serializable
@JvmInline
value class ReadSource(val rawValue: String) {
    companion object {
        val visible = ReadSource("visible")
        val recent = ReadSource("recent")
        val recentUnwrapped = ReadSource("recent_unwrapped")
        val detection = ReadSource("detection")
    }
}

@Serializable
data class ServerCapabilities(
    @SerialName("detached_server_daemon")
    val detachedServerDaemon: Boolean? = null,
    @SerialName("live_handoff")
    val liveHandoff: Boolean
)

@Serializable
data class SessionSnapshot(
    val agents: List<AgentInfo>,
    @SerialName("focused_pane_id")
    val focusedPaneID: String? = null,
    @SerialName("focused_tab_id")
    val focusedTabID: String? = null,
    @SerialName("focused_workspace_id")
    val focusedWorkspaceID: String? = null,
    val layouts: List<PaneLayoutSnapshot>,
    val panes: List<PaneInfo>,
    @SerialName("protocol")
    val protocolVersion: Int,
    val tabs: List<TabInfo>,
    val version: String,
    val workspaces: List<WorkspaceInfo>
)

@Serializable
data class SessionSnapshotResponse(
    val snapshot: SessionSnapshot
)

@Serializable
@JvmInline
value class SplitDirection(val rawValue: String) {
    companion object {
        val right = SplitDirection("right")
        val down = SplitDirection("down")
    }
}

@Serializable
class SubscriptionStartedResponse

@Serializable
data class TabCreateParams(
    val cwd: String? = null,
    val env: Map<String, String>? = null,
    val focus: Boolean? = null,
    val label: String? = null,
    @SerialName("workspace_id")
    val workspaceID: String? = null
)

@Serializable
data class TabCreatedResponse(
    @SerialName("root_pane")
    val rootPane: PaneInfo,
    val tab: TabInfo
)

@Serializable
data class TabInfo(
    @SerialName("agent_status")
    val agentStatus: AgentStatus,
    val focused: Boolean,
    val label: String,
    val number: Int,
    @SerialName("pane_count")
    val paneCount: Int,
    @SerialName("tab_id")
    val tabID: String,
    @SerialName("workspace_id")
    val workspaceID: String
)

@Serializable
data class WorkspaceInfo(
    @SerialName("active_tab_id")
    val activeTabID: String,
    @SerialName("agent_status")
    val agentStatus: AgentStatus,
    val focused: Boolean,
    val label: String,
    val number: Int,
    @SerialName("pane_count")
    val paneCount: Int,
    @SerialName("tab_count")
    val tabCount: Int,
    val tokens: Map<String, String>? = null,
    @SerialName("workspace_id")
    val workspaceID: String,
    val worktree: WorkspaceWorktreeInfo? = null
)

@Serializable
data class WorkspaceInfoResponse(
    val workspace: WorkspaceInfo
)

@Serializable
data class WorkspaceRenameParams(
    val label: String,
    @SerialName("workspace_id")
    val workspaceID: String
)

@Serializable
data class WorkspaceWorktreeInfo(
    @SerialName("checkout_path")
    val checkoutPath: String,
    @SerialName("is_linked_worktree")
    val isLinkedWorktree: Boolean,
    @SerialName("repo_key")
    val repoKey: String,
    @SerialName("repo_name")
    val repoName: String,
    @SerialName("repo_root")
    val repoRoot: String
)

@Serializable
data class WorktreeCreateParams(
    val base: String? = null,
    val branch: String? = null,
    val cwd: String? = null,
    val focus: Boolean? = null,
    val label: String? = null,
    val path: String? = null,
    @SerialName("workspace_id")
    val workspaceID: String? = null
)

@Serializable
data class WorktreeCreatedResponse(
    @SerialName("root_pane")
    val rootPane: PaneInfo,
    val tab: TabInfo,
    val workspace: WorkspaceInfo,
    val worktree: WorktreeInfo
)

@Serializable
data class WorktreeInfo(
    val branch: String? = null,
    @SerialName("is_bare")
    val isBare: Boolean,
    @SerialName("is_detached")
    val isDetached: Boolean,
    @SerialName("is_linked_worktree")
    val isLinkedWorktree: Boolean,
    @SerialName("is_prunable")
    val isPrunable: Boolean,
    val label: String,
    @SerialName("open_workspace_id")
    val openWorkspaceID: String? = null,
    val path: String
)

@Serializable
data class WorktreeRemoveParams(
    val force: Boolean? = null,
    @SerialName("workspace_id")
    val workspaceID: String
)

@Serializable
data class WorktreeRemovedResponse(
    val forced: Boolean,
    val path: String,
    @SerialName("workspace_id")
    val workspaceID: String
)
